### ISSUE TITLE
https, cors 과제 제출합니다 (_ _)

### ISSUE THREAD

**Issue by lovehachiware** [likelion-Inha-12/lovehachiware#13]
**키워드 과제 1 
URL v.s. Origin v.s. Domain 각각의 개념은 무엇이고, 세 키워드 간의 관계는 어떻게 될까요?**

-> URL : 웹에서 자원을 찾기 위한 장소

origin(출처) : url 구조에서 프로토콜, 호스트, 포트를 합친 것. 자원의 출처.

Domain : ( = 인터넷 주소). 호스트명에서 도메인 부분. 보통 웹 사이트의 소유자를 나타냄. 여러 하위 도메인을 가질 수 있음.

->> URL은 전체 주소를 나타내고, 
그 중 Origin은 보안 측면에서 중요한 세부 정보만을 포함하며, Domain은 Host 부분의 특정 식별자를 의미. 
URL은 가장 포괄적인 개념이며, 
Origin은 URL의 중요한 보안 세그먼트, 
Domain은 그 안에서 웹사이트를 식별하는 부분.

**키워드 과제 2
https://lionz12.netlify.app과 아래의 URL을 비교하여 같은 출처인지, 다른 출처인지 그리고 그 이유는 무엇인지에 대해 간략하게 적어주세요!**

https://lionz12.netlify.app/homework		- 같은 출처 / origin이 동일하다.
https://lionz12.netlify.app/homework-submit/69	 - 같은 출처/ origin이 동일하다.
http://lionz12.netlify.app/homework	- 다른 출처 / 프로토콜이 다름 (http)
https://lionz12.seminar.com	- 다른 출처 / 도메인이 다름(seminar.com)

**키워드 과제 3
Access-Control-Allow-Origin : * 는 무슨 의미일지, 그리고 이렇게 설정한다면 무슨 일이 일어날지 생각해보세요!**

Access-Control-Allow-Origin 의 의미는 특정 리소스가 모든 도메인에서 접속할 수 있다는 뜻 + *은 모두 허용하겠다는 뜻.
-> 개발 초기나 테스트 단계에서 쉽게 CORS 문제를 해결할 수 있으나, 모든 도메인에 대한 접근을 허용하면 악의적인 도메인에서도 리소스를 사용할 수 있어 보안 취약점이 될 수 있고, 데이터가 유출될 수 있어 위험함.

**키워드 과제 4
CORS와 같이 어플리케이션에서 사용자 정보를 탈취하는 것을 막기 위한 정책인 CSRF(Cross-Site Request Forgery)가 무엇인지, django에서는 CSRF 공격을 어떻게 방어하는지도 알아보면 좋을 것 같아요**

-> CSRF(Cross-Site Request Forgery) : 특정 사용자를 대상으로 하지 않고, 불특정 다수를 대상으로 로그인된 사용자가 자신의 의지와는 무관하게 공격자가 의도한 행위(수정, 삭제, 등록, 송금 등)를 하게 만드는 공격.

**django에서 CSRF 공격을 방어하는 법** : CSRF 미들웨어, CSRF 토큰 생성 및 검증, 뷰 데코레이터 사용, MIDDLEWARE 설정에 'django.middleware.csrf.CsrfViewMiddleware'가 포함.

<img width="1318" alt="스크린샷 2024-05-22 오전 11 29 19" src="https://github.com/likelion-Inha-12/lovehachiware/assets/163387941/cb00c509-7b0c-401d-8b14-9c7a9b61fb22">

**Comment by juwon0403** [comment]
갈수록 실력이 느는 게 느껴지는 것 같아요 ㅎㅎ
과제 제출 아주 완벽합니다!!

수고 많으셨어요~~
